# Generated by Django 4.2.3 on 2023-12-06 12:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_mainbranch_files_alter_mainbranch_subfolder'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainbranch',
            name='dateInfo',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
