# Generated by Django 4.2.7 on 2023-12-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_mainbranch_dateinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainbranch',
            name='dateInfo',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
