# Generated by Django 4.2.7 on 2023-12-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_folderfiles_size_mb_mainbranch_size_mb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folderfiles',
            name='size_mb',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='mainbranch',
            name='size_mb',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='subfolder',
            name='size_mb',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=100, null=True),
        ),
    ]
